spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      nitial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000

    multiple:
      master:
        username: root
        password: 123456
        url: jdbc:mysql://172.17.0.2:3306/framework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
      slave_1:
        username: root
        password: 123456
        url: jdbc:mysql://172.17.0.2:3306/framework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
  redis:
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 0
    host: 172.17.0.3             # Redis服务器地址-docker内部地址
    port: 6379                   # Redis服务器连接端口
    password:                    # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8          # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8            # 连接池中的最大空闲连接
        max-wait: -1ms         # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5            # 连接池中的最小空闲连接
  rabbitmq:
    host: 172.17.0.4
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true   # 消息发送到交换机确认机制,是否确认回调
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

mybatis-plus:
  global-config:
    #是否刷新sql,修改mapper之后不用重启
    refresh: true
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.baomidou: debug

# 应用自定义配置
application:
  async:
    core-pool-size: 2
    max-pool-size: 50
    queue-capacity: 10000
    threadNamePrifix: zrtec-thread
  # By default CORS is disabled. Uncomment to enable.
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "token"
    allow-credentials: true
    max-age: 1800
  swagger:
    title: spring boot快速开发平台api-后台
    description: API是一个基于Rest规范的开发API平台,响应数据统一格式：其中code等于0成功，非0错误，错误信息见msg。{"code":0,"msg":"string","data":{}}
    license: Apache license
    version: 1.0
  #权限安全配置
  security:
    # Token 有效时间，单位秒
    tokenExpire: 86400
    # 客户默认初始密码
    defaultPassword: 123456
    # 默认超级管理员id,多个用逗号分隔
    adminIds: 1,2
    # 密码错误次数
    errorNum: 3
